# fly.toml app configuration file generated for jonas-blog-cl on 2023-06-09T19:33:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jonas-blog-cl"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"